<?php

namespace Modules\Teacher;

use App\User;
use Modules\ModuleServiceProvider;

class ModuleProvider extends ModuleServiceProvider
{
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }

    public function boot(){

    }
}
